version: "3.5"
services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile.django
    environment:
      - "TZ=Asia/Tokyo"
      - "LANGUAGE=ja"
      - "TEST_ENV=1"
    volumes:
      - "workdir:/work:rw"
    ports:
      - 8000-8004:8000-8004
    networks:
      - default
      - development

  scheduler:
    container_name: scheduler
    build:
      context: .
      dockerfile: Dockerfile.django
    environment:
      - "TZ=Asia/Tokyo"
      - "WORKER=2"
    volumes:
      - "workdir:/work:rw"
    ports:
      - 8100-8104:8100-8104
    networks:
      - default
      - development

  adhoc:
    container_name: adhoc
    build:
      context: .
      dockerfile: Dockerfile.django
    environment:
      - "TZ=Asia/Tokyo"
      - "WORKER=2"
    volumes:
      - "workdir:/work:rw"
    ports:
      - 8200-8204:8200-8204
    networks:
      - default
      - development

  redis:
    container_name: redis
    build:
      context: .
      dockerfile: Dockerfile.redis
    environment:
      - "REDIS_SERVICE_PORT=6379"
      - "REDIS_KEEPALIVE_TIME=300"
      - "REDIS_MAXCLIENT=2500"
      - "REDIS_MAXMEMORY=32mb"
      - "REDIS_DATABASECOUNT=8"
    ports:
      - "6379:6379"
    command: confd -backend env
    volumes:
      #- ./conf.d/:/etc/mysql/conf.d
      #- ./initdb/:/docker-entrypoint-initdb.d
      - redisstore:/data

  #user1db:
  #  container_name: user1db
  ##  image: mysql:5.7
  #  environment:
  #    COMPOSE_CONVERT_WINDOWS_PATHS: 1
  #    MYSQL_ROOT_PASSWORD: mysecret
  #    MYSQL_USER: dbuser
  #    MYSQL_PASSWORD: dbuser
  #    MYSQL_DATABASE: user1
  #  command: --innodb-use-native-aio=0
  #  volumes:
  #    - ./conf.d/:/etc/mysql/conf.d
  #    - ./initdb/:/docker-entrypoint-initdb.d
  #    - userdb1store:/var/lib/mysql

  cassandra:
    container_name: cassandra
    image: cassandra:latest
    environment:
      COMPOSE_CONVERT_WINDOWS_PATHS: 1
      #CASSANDRA_LISTEN_ADDRESS: mysecret
      #CASSANDRA_BROADCAST_ADDRESS: dbuser
      #CASSANDRA_RACK: dbuser
      #CASSANDRA_SEEDS: fixdb
    #command: --innodb-use-native-aio=0
    volumes:
      #- ./conf.d/:/etc/mysql/conf.d
      #- ./initdb/:/docker-entrypoint-initdb.d
      - cassandrastore:/var/lib/cassandra

  defaultdb:
    container_name: defaultdb
    image: mysql:5.7
    #restart: always
    environment:
      COMPOSE_CONVERT_WINDOWS_PATHS: 1
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
      MYSQL_DATABASE: tigui
    command: --innodb-use-native-aio=0
    volumes:
      - ./conf.d/:/etc/mysql/conf.d
      - ./initdb/:/docker-entrypoint-initdb.d
      - datastore:/var/lib/mysql
    ports:
      - "23306:3306"
    networks:
      - default
      - development

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - default
      - development

  minio:
    container_name: minio
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio
    command: server http://minio{1...4}/export
    volumes:
      - s3store:/export
    ports:
      - "9000:9000"
    networks:
      - default
      - development

  emq:
    container_name: emq
    build:
      context: .
      dockerfile: Dockerfile.elasticmq
    command: /usr/local/bin/confd -backend env
    environment:
      ELASTICMQ_SERVICE_PORT: 9324
    volumes:
      - mqstore:/export
    ports:
      - "9324:9324"
    networks:
      - default
      - development

volumes:
  workdir:
    driver_opts:
      type: none
      device: /c/Users/$USERNAME/volumes/work
      o: bind
  datastore:
    driver_opts:
      type: none
      device: /c/Users/$USERNAME/volumes/datastore
      o: bind
  userdb1store:
    driver_opts:
      type: none
      device: /c/Users/$USERNAME/volumes/userdb1store
      o: bind
  redisstore:
    driver_opts:
      type: none
      device: /c/Users/$USERNAME/volumes/redisstore
      o: bind
  fixdbstore:
    driver_opts:
      type: none
      device: /c/Users/$USERNAME/volumes/fixdbstore
      o: bind
  cassandrastore:
    driver_opts:
      type: none
      device: /c/Users/$USERNAME/volumes/cassandrastore
      o: bind
  s3store:
    driver_opts:
      type: none
      device: /c/Users/$USERNAME/volumes/s3store
      o: bind
  mqstore:
    driver_opts:
      type: none
      device: /c/Users/$USERNAME/volumes/mqstore
      o: bind

networks:
  development:
    external: true
